version: "3.3"

services:
  bot:
    build: .
    container_name: telegram-bot
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - bot-network
    restart: always
    command: python bot.py

  web-ui:
    build: .
    container_name: web-ui
    volumes:
      - .:/app
      - ./data:/app/data
      - /etc/letsencrypt/live/${domain}:/etc/letsencrypt/live/${domain}:ro
      - /etc/letsencrypt/archive/${domain}:/etc/letsencrypt/archive/${domain}:ro

    networks:
      - bot-network
    restart: always
    ports:
      - "1110:1110"  

    environment:
      DB_PATH: /app/data/detail.db  
    command: python web-ui.py

  api:
    build: .
    container_name: api
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - bot-network
    restart: always
    ports:
      - "7386:7386"  
    environment:
      DB_PATH: /app/data/detail.db  
    command: uvicorn api:app --host 0.0.0.0 --port 7386

networks:
  bot-network:
    driver: bridge
