version: "3.8"
services:
  bot:
    build: .
    container_name: telegram-bot
    volumes:
      - .:/app
      - ./data:/app/data  
    networks:
      - bot-network
    restart: always
    ports:
      - "8000:8000"  
networks:
  bot-network:
    driver: bridge
