version: "3.8"
services:
  bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    volumes:
      - .:/app  # پوشه پروژه روی سیستم میزبان به داخل کانتینر متصل می‌شود
      - ./data:/app/data  # این خط باعث می‌شود پوشه 'data' روی میزبان به کانتینر متصل شود
    networks:
      - bot-network
    restart: always
    ports:
      - "8000:8000"  # اگر نیاز به پورت خاصی دارید، این را تنظیم کنید

networks:
  bot-network:
    driver: bridge
